//
//  StyleKitName.cs
//  iPod
//
//  Created by Jonathan French on 03/01/2017.
//  Copyright (c) 2017 JPF. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



using System;
using System.Drawing;
using Foundation;
using UIKit;
using CoreGraphics;

namespace iPod
{
    [Register ("StyleKitName")]
    public class StyleKitName : NSObject
    {

        //// Cache

        private static UIImage imageOfPlayButton;
        private static NSObject[] playButtonTargets;
        private static UIImage imageOfPauseButton;
        private static NSObject[] pauseButtonTargets;

        //// Initialization

        static StyleKitName()
        {
        }

        //// Drawing Methods

        public static void DrawPlayButton()
        {
            //// General Declarations
            var context = UIGraphics.GetCurrentContext();

            //// Polygon Drawing
            context.SaveState();
            context.TranslateCTM(30.0f, 30.0f);
            context.RotateCTM(90.0f * NMath.PI / 180.0f);

            UIBezierPath polygonPath = new UIBezierPath();
            polygonPath.MoveTo(new CGPoint(0.0f, -25.0f));
            polygonPath.AddLineTo(new CGPoint(21.65f, 12.5f));
            polygonPath.AddLineTo(new CGPoint(-21.65f, 12.5f));
            polygonPath.ClosePath();
            UIColor.Black.SetFill();
            polygonPath.Fill();

            context.RestoreState();
        }

        public static void DrawPauseButton()
        {

            //// Rectangle Drawing
            var rectanglePath = UIBezierPath.FromRect(new CGRect(15.0f, 5.0f, 10.0f, 50.0f));
            UIColor.Black.SetFill();
            rectanglePath.Fill();


            //// Rectangle 2 Drawing
            var rectangle2Path = UIBezierPath.FromRect(new CGRect(35.0f, 5.0f, 10.0f, 50.0f));
            UIColor.Black.SetFill();
            rectangle2Path.Fill();
        }

        //// Generated Images

        public static UIImage ImageOfPlayButton
        {
            get
            {
                if (imageOfPlayButton != null)
                    return imageOfPlayButton;

                UIGraphics.BeginImageContextWithOptions(new CGSize(60.0f, 60.0f), false, 0);
                                StyleKitName.DrawPlayButton();

                imageOfPlayButton = UIGraphics.GetImageFromCurrentImageContext();
                UIGraphics.EndImageContext();

                return imageOfPlayButton;
            }
        }

        public static UIImage ImageOfPauseButton
        {
            get
            {
                if (imageOfPauseButton != null)
                    return imageOfPauseButton;

                UIGraphics.BeginImageContextWithOptions(new CGSize(60.0f, 60.0f), false, 0);
                                StyleKitName.DrawPauseButton();

                imageOfPauseButton = UIGraphics.GetImageFromCurrentImageContext();
                UIGraphics.EndImageContext();

                return imageOfPauseButton;
            }
        }

        //// Customization Infrastructure

        [Outlet]
        public NSObject[] PlayButtonTargets
        {
            get { return playButtonTargets; }
            set
            {
                playButtonTargets = value;
                foreach (NSObject target in value)
                {
                    target.PerformSelector(new ObjCRuntime.Selector("setImage:"), ImageOfPlayButton, 0);
                }
            }
        }

        [Outlet]
        public NSObject[] PauseButtonTargets
        {
            get { return pauseButtonTargets; }
            set
            {
                pauseButtonTargets = value;
                foreach (NSObject target in value)
                {
                    target.PerformSelector(new ObjCRuntime.Selector("setImage:"), ImageOfPauseButton, 0);
                }
            }
        }

    }
}
